### ISSUE TITLE
Potential bug in game play causes 'Game Over' for no 'visible' reason

### ISSUE THREAD

**Issue by bj7** [ASGMarketing/https-github.com-blakbro2k-DantesEscape#2]
Occasionally when playing, I get a game over for no _visible_ reason. My guess is something doesn't render properly, but I see no log errors currently.

**Comment by bj7** [comment]
Ok I found the _bug_, turns out it's a stalagmite or stalactite that isn't rendered, or maybe my eyes are just bad. The debug boxes helped a lot.

**Comment by bj7** [comment]
Think I see the issue; stalagmites do not want to render through the lava. All stalactites render properly.

**Comment by blakbro2k** [comment]
try downloading the latest version of the code

**Comment by blakbro2k** [comment]
I just tagged a v0.0.1 release which I know should not have this bug in it.
